language: ruby
cache: bundler
gemfile: Gemfile
os: linux
dist: focal

script:
  - bundle install
  - bundle exec jekyll build --source ./ --destination ./_site --trace

after_script:
  - bash .travis/tg_notify.sh

before_deploy:
  - ls -la

deploy:
  - provider: pages
    #Push to different repo
    repo: thelitblog/thelitblog.github.io
    # Directory where your generated files are located
    local_dir: ./_site/
    # Github security/auth token
    github-token: $GITHUB_TOKEN
    # Incremental commit to keep old build/files from previous deployments
    keep-history: true
    # Git branch on which it should deploy (master, gh-pages, foo...)
    target_branch: inverse
    # Reminder that I was dumb
    skip_cleanup: true
    on:
      # Which branch on commit/push will trigger deployment
      branch: inverse

  - provider: pages
    #Push to different repo
    repo: thelitblog/thelitblog.github.io
    # Directory where your generated files are located
    local_dir: _site
    # Github security/auth token
    github-token: $GITHUB_TOKEN
    # Incremental commit to keep old build/files from previous deployments
    keep-history: true
    #Reminder that I was dumb
    skip_cleanup: true
    # Git branch on which it should deploy (master, gh-pages, foo...)
    target_branch: main
    on:
      # Which branch on commit/push will trigger deployment
      branch: master
rvm:
  - 2.4


