language: ruby
cache: bundler
gemfile: Gemfile
os: linux
dist: focal
script:
- bundle install
- bundle exec jekyll build --source ./ --destination ./_site --trace
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bash
  .travis/push.sh; fi
rvm:
- 2.4
before_install:
- openssl aes-256-cbc -K $encrypted_75e4c4238592_key -iv $encrypted_75e4c4238592_iv
  -in ./.travis/id.pem.enc -out ./.travis/id.pem -d
