language: ruby
cache: bundler
gemfile: Gemfile
os: linux
dist: focal
script:
- bundle install
- bundle exec jekyll build --source ./ --destination ./_site --trace

deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      branch: master
  - provider: script
    script: bash .travis/shift-push.sh
    on:
      branch: inverse
rvm:
- 2.4
