language: ruby
cache: bundler
gemfile: Gemfile
os: linux
dist: focal

script:
  - bundle install
  - bundle exec jekyll build --source ./ --destination ./gen_site --trace
  - ls -la
  - echo "After install"

after_script:
  - bash .travis/tg_notify.sh

before_deploy:
  - ls -la

deploy:
  - provider: pages
    #Push to different repo
    repo: thelitblog/thelitblog.github.io
    # Directory where your generated files are located
    local_dir: gen_site
    # Github security/auth token
    github-token: $GITHUB_TOKEN
    # Incremental commit to keep old build/files from previous deployments
    keep-history: true
    # Git branch on which it should deploy (master, gh-pages, foo...)
    target_branch: inverse
    on:
      # Which branch on commit/push will trigger deployment
      branch: inverse

  - provider: pages
    #Push to different repo
    repo: thelitblog/thelitblog.github.io
    # Directory where your generated files are located
    local_dir: gen_site
    # Github security/auth token
    github-token: $GITHUB_TOKEN
    # Incremental commit to keep old build/files from previous deployments
    keep-history: true
    # Git branch on which it should deploy (master, gh-pages, foo...)
    target_branch: main
    on:
      # Which branch on commit/push will trigger deployment
      branch: master
rvm:
  - 2.4

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
